# Generated by Django 3.2.2 on 2021-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_foreign', models.CharField(max_length=50, unique=True)),
                ('title_native', models.CharField(max_length=50)),
                ('context', models.TextField(max_length=100)),
            ],
        ),
    ]
