# Generated by Django 3.2.2 on 2021-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='context',
            new_name='context_native',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='title_foreign',
            new_name='word_foreign',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='title_native',
            new_name='word_native',
        ),
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='context_foreign',
            field=models.TextField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='score',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
