# Generated by Django 3.2.2 on 2021-05-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20210509_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_foreign', models.CharField(max_length=50, unique=True)),
                ('word_native', models.CharField(max_length=50)),
                ('context_foreign', models.TextField(max_length=100, unique=True)),
                ('context_native', models.TextField(max_length=100)),
                ('audio', models.FileField(upload_to='media/')),
                ('score', models.IntegerField()),
                ('dictionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='dict.dictionary')),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
