# Generated by Django 3.2.2 on 2021-05-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20210510_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='audio',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='context_foreign',
            field=models.TextField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='context_native',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
