# Generated by Django 3.2.2 on 2021-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20210510_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
