# Generated by Django 3.2.2 on 2021-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_dictionary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
