# Generated by Django 3.2.2 on 2021-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_alter_dictionary_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcard',
            name='is_learning',
            field=models.BooleanField(default=False),
        ),
    ]
