# Generated by Django 3.2.2 on 2021-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_wordcard_is_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='words_to_learn',
            field=models.IntegerField(default=20),
        ),
    ]
