# Generated by Django 3.2.2 on 2021-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_dictionary_words_to_learn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordcard',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveField(
            model_name='wordcard',
            name='audio',
        ),
        migrations.AddField(
            model_name='wordcard',
            name='context_foreign_audio',
            field=models.FileField(blank=True, upload_to='media/context'),
        ),
        migrations.AddField(
            model_name='wordcard',
            name='word_foreign_audio',
            field=models.FileField(blank=True, upload_to='media/word'),
        ),
    ]
