# Generated by Django 3.2.2 on 2021-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0009_auto_20210512_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
