# Generated by Django 3.2.2 on 2021-05-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0010_temporaryword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='context_foreign',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
