# Generated by Django 3.2.2 on 2021-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_alter_wordcard_context_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcard',
            name='last_learn_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
