# Generated by Django 3.2.2 on 2021-05-15 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_wordcard_last_learn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='last_learn_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 10, 23, 25, 19601)),
        ),
    ]
