# Generated by Django 3.2.2 on 2021-05-15 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0015_alter_wordcard_last_learn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='last_learn_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 11, 1, 14, 633284, tzinfo=utc)),
        ),
    ]
